import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { fetchStockData, fetchStockDetails } from "../../util/stocks-api";
import DashboardNav from "../DashboardNavbar";
import LineChart from "../LineChart";
import NewsArticle from "../NewsArticle";
import BuySellForm from "./BuySellForm";
import KeyStatistics from "./KeyStatistics";

function DetailsPage() {
    const { symbol } = useParams()
    const [isLoaded, setIsLoaded] = useState(false)
    const [assetDetails, setAssetDetails] = useState()
    const [assetQuote, setAssetQuote] = useState()
    const [news, setNews] = useState()

    useEffect(() => {
        // const getDetails = async () => {
        //     return await fetchStockDetails(symbol)
        // }
        // const details = getDetails();

        // const getQuote = async () => {
        //     return await fetchStockData(symbol)
        // }
        // const quote = getQuote();

        const getNews = async () => {
            let res = await fetch("/api/finnhub/market-news");
            let data = await res.json();
            let topNews = data.slice(0, 3);
            setNews(topNews);
        };
        getNews();

        const details = {
            "Symbol": "IBM",
            "AssetType": "Common Stock",
            "Name": "International Business Machines",
            "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
            "CIK": "51143",
            "Exchange": "NYSE",
            "Currency": "USD",
            "Country": "USA",
            "Sector": "TECHNOLOGY",
            "Industry": "COMPUTER & OFFICE EQUIPMENT",
            "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
            "FiscalYearEnd": "December",
            "LatestQuarter": "2022-06-30",
            "MarketCapitalization": "122401456000",
            "EBITDA": "12159000000",
            "PERatio": "22.43",
            "PEGRatio": "1.85",
            "BookValue": "21.49",
            "DividendPerShare": "6.58",
            "DividendYield": "0.0483",
            "EPS": "6.09",
            "RevenuePerShareTTM": "66.38",
            "ProfitMargin": "0.0936",
            "OperatingMarginTTM": "0.111",
            "ReturnOnAssetsTTM": "0.03",
            "ReturnOnEquityTTM": "0.271",
            "RevenueTTM": "59679998000",
            "GrossProfitTTM": "31486000000",
            "DilutedEPSTTM": "6.09",
            "QuarterlyEarningsGrowthYOY": "0.041",
            "QuarterlyRevenueGrowthYOY": "0.093",
            "AnalystTargetPrice": "143.18",
            "TrailingPE": "22.43",
            "ForwardPE": "14.66",
            "PriceToSalesRatioTTM": "2.051",
            "PriceToBookRatio": "6.35",
            "EVToRevenue": "2.834",
            "EVToEBITDA": "13.22",
            "Beta": "0.853",
            "52WeekHigh": "142.93",
            "52WeekLow": "110.45",
            "50DayMovingAverage": "135.74",
            "200DayMovingAverage": "130.65",
            "SharesOutstanding": "896320000",
            "DividendDate": "2022-09-10",
            "ExDividendDate": "2022-08-09"
        }

        const quote = {
            "c": 137.79,
            "d": 1.23,
            "dp": 0.9007,
            "h": 138.415,
            "l": 136.3,
            "o": 136.46,
            "pc": 136.56,
            "t": 1660766402
        }

        setAssetDetails(details)
        setAssetQuote(quote)
        setIsLoaded(true)
    }, [])


    return isLoaded && (
        <div>
            <DashboardNav />
            <div className="details-page-left-container">
                <div className="details-page-graph-container">
                    <LineChart />
                </div>
                <div className="details-page-about">
                    <h3>About</h3>
                    <p>
                        {assetDetails.Description}
                    </p>
                    {/* <div className="details-page-about-tidbits-container">
                        <div className="details-page-about-tidbit">
                            <div>
                                CEO
                            </div>
                            <div>
                                { }
                            </div>
                        </div>
                        <div className="details-page-about-tidbit">
                            <div>
                                Employees
                            </div>
                            <div>
                                { }
                            </div>
                        </div>
                        <div className="details-page-about-tidbit">
                            <div>
                                Headquarters
                            </div>
                            <div>
                                { }
                            </div>
                        </div>
                        <div className="details-page-about-tidbit">
                            <div>
                                Founded
                            </div>
                            <div>
                                { }
                            </div>
                        </div>
                    </div> */}
                </div>
                <div className="details-page-about-key-statistics-container">
                    <KeyStatistics details={assetDetails} quote={assetQuote} />
                </div>
                <div className="details-page-news-container">
                    {/* <NewsArticle /> */}
                    NEWS ARTICLES GO HERE
                </div>
            </div>
            <div className="details-page-right-container">
                <BuySellForm quote={assetQuote} />
                <button>
                    + Add to Lists
                </button>
            </div>
        </div>
    );
}

export default DetailsPage;
