"""create tables

Revision ID: 2f567148e94a
Revises:
Create Date: 2022-08-19 21:10:45.001606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f567148e94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('buying_power', sa.Float(
                        precision=2), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('portfolios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbol', sa.String(length=5), nullable=False),
                    sa.Column('quantity_owned', sa.Integer(), nullable=False),
                    sa.Column('total_purchase_price', sa.Float(
                        precision=2), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbol', sa.String(length=5), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(precision=2), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('watchlists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=15), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('watchlist_stocks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbol', sa.String(length=5), nullable=False),
                    sa.Column('watchlist_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['watchlist_id'], ['watchlists.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    op.drop_table('watchlists')
    op.drop_table('transactions')
    op.drop_table('portfolios')
    op.drop_table('users')
    # ### end Alembic commands ###
